### ISSUE TITLE
426 ошибка при выполнении uploader download

### ISSUE THREAD

**Issue by mdd-github** [insales/insales-uploader#13]
При использовании uploader, невозможно скачать проект. Данные корректные

В терминал падает следующее:
```
[01:34:58] theme:download:start
undefined
C:\Projects\ecoline\node_modules\insales-uploader\dist\insalesApi\updateAssets.js:66
      var status = headers.status;
                           ^

TypeError: Cannot read property 'status' of undefined
    at C:\Projects\ecoline\node_modules\insales-uploader\dist\insalesApi\updateAssets.js:66:28
```

При вставке reject(err) в начале catch блока промиса в ф-ии updateAssets - показывает 426 статус-код. 

Возможно это связано с обновлениями InSales - магазин созданный ранее качает, хоть и выводит ту же ошибку, только что созданный магазин - отказывается.

**Comment by VladimirIvanin** [comment]
Для новых аккаунтов в тарифе "Стандартный" отключен доступ к API.
Поменяйте тариф в настройках аккаунта
