### ISSUE TITLE
Поддержка browser-sync

### ISSUE THREAD

**Issue by diproart** [insales/insales-uploader#3]
Как можно использовать browser-sync в новой версии. 
Можно ли добавить примеры?

**Comment by VladimirIvanin** [comment]
Тут есть пример с колбеком в методе `stream`
https://github.com/VladimirIvanin/gulp-inSales-uploader

В обычных настройках можно использовать колбек `onUpdate`
```js
module.exports = {
  account: {
    // id: '11111111111111111111111111',
    // token: '222222222222222222222',
    // url: 'shop-41254.myinsales.ru'
  },
  theme:{
    //id: '854716',
    onUpdate: ()=>{
      // обновление темы
    }
  }
}
```

Примеры добавлю вместе с описанием настроек.

**Comment by diproart** [comment]
это тоже самое, что и `worker.stream(callback)`?

> Конечно можно запускать через proxy и нет проблем, я всё понимаю, и видео красивое есть на Youtube и сайт, но приходиться задавать вопросы,  есть сотрудники, верстальщики и требования к локальному окружению. Можно работать и через облако, но если есть инструмент и он анонсирован, переведен в официальный репозиторий, на "ютубе говорят" приходи...

p.s. или  тоже в `коде` посмотреть...

**Comment by VladimirIvanin** [comment]
Добавил описание

https://github.com/insales/insales-uploader/blob/master/recipes/browsersync.md
