### ISSUE TITLE
Кастомная сборка

### ISSUE THREAD

**Issue by MrLogaz** [insales/insales-uploader#6]
Добрый день.

Возможно ли создание кастомной сборки проекта, которую можно будет встроить в крайне удобную синхронизацию по средствам stream. 
Сейчас я это вижу только как pull -> сборка -> push, но очень хочется сразу работать с шаблоном на сайте.

Например я хотел бы выполнять:
1) минификацию стилей, которой либо нет, либо я не нашел. Сейчас например стили как есть и еще дополнительно содержат ненужные в продакшене комментарии  /* line X, _file.scss */
2) Использование не только scss.
3) Минифицировать и обфусцировать скрипты.

Если это все уже можно, то подскажите каким образом это реализуется?

**Comment by VladimirIvanin** [comment]
Добрый день!

Можно подключать gulp плагины.
Например как тут:
[gulpfile.js](https://github.com/VladimirIvanin/gulp-inSales-uploader/blob/master/gulpfile.js)

или тут
[insales-config.js](https://github.com/insales-uploader/uploader-work-space/blob/a83e505e492e235204392950c9618ed682d91b79/insales-config.js#L42)

Инструмент в виде сборщика сейчас тестируется и как будут готовы все его компоненты я сделаю анонс на [youtube канале](https://www.youtube.com/channel/UCs6isk1giWZS33EyactK68w).

В любом случае нужно понимать такие моменты:
- через uploader не получится создавать тему в магазине.
- минифицируя вы должны помнить, что с этой темой будет работать кто нибудь ещё, стоит сообщать клиенту, что вы минифицировали/обфусцировали код и исходники у вас.
- вы можете написать свой сборщик и просто в dist/dest/output указывать директорию аплоадера (это может решить вопрос с scss, в InSales scss просто нативно встроен и всегда будет добавлять ```/* line X, _file.scss */```).

**Comment by MrLogaz** [comment]
Спасибо за ответ.

То что uploader не создает темы я понимаю, но было бы интересным решением подключать к insales git репозиторий и использовать ветки в качестве тем. Если грубо взглянуть, то темы сейчас примерно так и работают. Отделять какие-то задачные ветки от тем можно было бы по наименованию. Например если имя ветки начинается с theme_xxxxxx.

Касательно сборщика. Могу ли я создавать новые директории в проекте, что я мог бы использовать в качестве src, при этом сохраняя исходники в пределах темы. В таком случае я мог бы запускать uploader stream и параллельно запускать свой сборщик с выходными файлами в assets/style | js

**Comment by VladimirIvanin** [comment]
Свои директории в теме создавать нельзя, для отдельной задачи используйте копии темы.
