### ISSUE TITLE
Пропадают/появляются файлы на сервере

### ISSUE THREAD

**Issue by ivangretsky** [insales/insales-uploader#8]
Добрый день!

Настроил проект и начал работать (запустив gulp stream). Изменения происходят. Но после некоторого времени работы на сервере начал пропадать файлы снипетов и шаблонов. При этом локально они есть, с ними не работали. Затем часть файлов вновь загрузились на сервер (на данный момент не все). Почему может просиходит удаление/загрузка файлов, которые не менялись локально?

**Comment by ivangretsky** [comment]
В логах постоянно появляются сообщения о редактировании файлов, которые не редактировались (во всяком случае, вручную).

**Comment by VladimirIvanin** [comment]
Опишите больше информации. 
Какая ОС/Версия node.js?
Может скриншоты есть?
Через какой терминал запускаете?
Сколько терминалов запущено?

**Comment by ivangretsky** [comment]
Проблема возникает при запуске в WSL на Windows 10.
