### ISSUE TITLE
Выгрузка одного файла / только одного файла

### ISSUE THREAD

**Issue by max-mal** [insales/insales-uploader#9]
Здравствуйте, есть ли возможность выгрузить один единственный файл / список измененных файлов, взятый из git

При попытке выгрузки файла с помощью скрипта ниже, файл выгружается, изменения видны в админ-панели, однако не происходит перегенерация asset`ов, если были изменены css файлы. При этом, если измнять файлы .liquid, то все изменения применяются корректно

Не могли бы вы подсказать, что делается не так и почему не происходит перегенерация asset`ов? 

Также примечательно то, что после выгрузки файла скриптом перегенерация не происходит, даже если поменять файл в админ панеле Insales. С чем это может быть связано?

`const uploader = require('insales-uploader');

const options = require('./insales-config.js');

const IU = new uploader(options);

IU.src(process.argv[2]).pipe(IU.dest());
`

**Comment by VladimirIvanin** [comment]
Добрый день!
Возможно ошибка в scss файлах 
https://youtu.be/bTMVWSotwe8?t=62
На видео показано как найти ошибку
